#management:
#  security:
#    enabled: false
#  endpoints:
#    enabled-by-default: true
#  endpoint:
#    exposure:
#      include: "*"
#    health:
#      enabled: true
#      show-details: always
#    info:
#      enabled: true
